F/backend/phi
larsk21/compiler-minijava pull request #99
Opened 2021-12-22 21:32 UTC by 0xNB

2021-12-23 09:29 UTC, g4rgoil requested changes
Are currently dealing with the instruction generated by `ExitCondition` in some way?

2021-12-23 09:29 UTC, g4rgoil commented on src/main/java/edu/kit/compiler/codegen/BasicBlocks.java
> +            return instructions;
There is a reason why this originally returned an unmodifiable list. You're not really supposed to change the state of this class. For example, I'm currently considering breaking `instructions` into two lists. You're change here makes that pretty much impossbile.

2021-12-23 09:29 UTC, g4rgoil commented on src/main/java/edu/kit/compiler/codegen/PhiRemover.java
> +    public BasicBlocks removePhis() {
I would have expected your code to receive an instance of `BasicBlocks` and return some kind of `Map<Integer, List<Instruction>>` (which is what we need for register allocation).

2021-12-23 09:29 UTC, g4rgoil commented on src/main/java/edu/kit/compiler/codegen/PhiRemover.java
> +            List<PhiAssignment> permutations = permutationSolver.solve(new PhiSourceNodeRegister(maxRegister, nullNode));
You seem to be using `maxRegister` for spilling. However, as far as I can tell, there is no guarantee, that register isn't used elsewhere. I'm sure I can expose my register counter to you somehow, so you can properly allocate the temporary register.

2022-01-02 20:17 UTC, N-Maas commented
Replaced by #103

2022-01-02 20:17 UTC, closed without merging